package first;

public class ExceptionHandling {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("this is main starting");
		int arr[] = {10,20,30,40};
		try {
		System.out.println("print arr[2]"+arr[20]);
		}
		catch(ArrayIndexOutOfBoundsException aref) {
			System.out.println("array out of bounds exception");
			
		}

	}

}
